version: '3.8'

services:

 # web server service
  kitchen_nginx:
    image: nginx:alpine
    container_name: kitchen_nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - kitchen_app
      - kitchen_db 
    networks:
      - lunch

  # database service
  kitchen_db:
    image: postgres
    container_name: kitchen_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: Kitchen
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - lunch

  # apllication service
  kitchen_app:
    container_name: kitchen_app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9001:9000"
    working_dir: /var/www
    networks:
      - lunch

  # pg service
  kitchen_pgadmin:
    image: dpage/pgadmin4
    container_name: kitchen_pgadmin
    ports:
      - "5051:80"
    depends_on:
      - kitchen_db
    environment:
      PGADMIN_DEFAULT_EMAIL: fabiobetancourt7@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - lunch

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - lunch
  
networks:
  lunch:
    external: true

  